(set ($$quote *language*) "Scheme")
(set ($$quote *implementation*) "chibi-scheme")
(set ($$quote *port*) "0.1")
(set ($$quote *porters*) "Bruno Deferrari")
(set ($$quote *stinput*) ($$current-input-port))
(set ($$quote *stoutput*) ($$current-output-port))
($$set-shen-environment! ($$current-environment))
