(define-library (shen reader)
  (import (except (scheme base) read-string)
          (scheme char) (scheme file)
          (only (chibi) call-with-input-string))
  (export read-kl read-kl-file)
  (include "reader.scm"))
